spring:
  profiles:
    active: release

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'api-design'
      paths-to-match: '/**'
      packages-to-scan: com.example.ex3_2_back